version: "3.7"

services:
  flask-app:
    image: flask-image
    build: ./flask-tutorial
    container_name: flask-container
    ports:
      - "7777:8080"

  django-app:
    image: django-image
    build: ./backend
    container_name: django-container
    # si cambias el puerto "x" ("x":8000) tambien tienes que cambiar el comando:
    # python3 manage.py runserver 0.0.0.0:"x"
    ports:
      - "8000:8000"
    # depende de redis porque si no levanta redis primero
    # este app se cae
    depends_on:
      - redis-app

  react-app:
    image: react-image
    build: ./frontend2
    container_name: react-container
    ports:
      - "3000:3000"

  redis-app:
    image: redis:6.2.6
    container_name: redis_container
    ports:
      - "6379:6379"


